# Site settings
author: Jeremy Snelson
title: 
header-img: img/home-bg.png
email: jeremy_snelson@dpsk12.org
copyright_name: Jeremy Snelson
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jerboski

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
